# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.consult <- function(files) {
    .Call('_rswipl_consult_', PACKAGE = 'rswipl', files)
}

.query <- function(query) {
    .Call('_rswipl_query_', PACKAGE = 'rswipl', query)
}

.clear <- function() {
    .Call('_rswipl_clear_', PACKAGE = 'rswipl')
}

.submit <- function() {
    .Call('_rswipl_submit_', PACKAGE = 'rswipl')
}

.once <- function(query) {
    .Call('_rswipl_once_', PACKAGE = 'rswipl', query)
}

.findall <- function(query) {
    .Call('_rswipl_findall_', PACKAGE = 'rswipl', query)
}

.portray <- function(query) {
    .Call('_rswipl_portray_', PACKAGE = 'rswipl', query)
}

.call <- function(query) {
    .Call('_rswipl_call_', PACKAGE = 'rswipl', query)
}

.init <- function(argv0) {
    .Call('_rswipl_init_', PACKAGE = 'rswipl', argv0)
}

.done <- function() {
    .Call('_rswipl_done_', PACKAGE = 'rswipl')
}

