# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.query <- function(query) {
    .Call('_rswipl_query_', PACKAGE = 'rswipl', query)
}

.clear <- function() {
    .Call('_rswipl_clear_', PACKAGE = 'rswipl')
}

.submit <- function() {
    .Call('_rswipl_submit_', PACKAGE = 'rswipl')
}

.init <- function(argv0) {
    .Call('_rswipl_init_', PACKAGE = 'rswipl', argv0)
}

.done <- function() {
    .Call('_rswipl_done_', PACKAGE = 'rswipl')
}

