# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.init <- function(argv0) {
    .Call('_rswipl_init_', PACKAGE = 'rswipl', argv0)
}

.done <- function() {
    .Call('_rswipl_done_', PACKAGE = 'rswipl')
}
